name: System-Check-Task

on:
  workflow_dispatch: # Permet de lancer le bot à la main quand TU le décides

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execution
        run: |
          docker build -t system-task .
          # On garde le timeout pour la sécurité, mais il n'y aura plus de relance auto
          timeout 355m docker run system-task
