name: System-Check-Task
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Se relance toutes les 6 heures

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execution
        run: |
          docker build -t system-task .
          # Tourne pendant 355 minutes (juste avant la relance auto)
          timeout 355m docker run system-task
